# http://docs.travis-ci.com/user/languages/r/

language: r

before_install:
  - sudo apt-get install libv8-dev

#to skip warning about compression
warnings_are_errors: false

r_binary_packages:
 - rgdal

  